// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBviGgAXy8zIgCxQnPxDvmE-nrESz5It8o',
    appId: '1:960856632630:web:9c5682429f6e0c4787d797',
    messagingSenderId: '960856632630',
    projectId: 'tiktok-clone-a34d1',
    authDomain: 'tiktok-clone-a34d1.firebaseapp.com',
    storageBucket: 'tiktok-clone-a34d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNAag1IWeZLdnvLAMN3H7WKx1X0nKteg',
    appId: '1:197147642320:android:f1d4c41170394651bfd1d5',
    messagingSenderId: '197147642320',
    projectId: 'tictok-27c2b',
    storageBucket: 'tictok-27c2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZtbPyv9DKSVMKBACkDWi5wceW4o37O4',
    appId: '1:197147642320:ios:94971a28c88419a8bfd1d5',
    messagingSenderId: '197147642320',
    projectId: 'tictok-27c2b',
    storageBucket: 'tictok-27c2b.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

}